
BUILD_DIR = build
TARGET    = BK3633_BIM

AR = arm-none-eabi-gcc-ar
CC = arm-none-eabi-gcc

CCFLAGS  = -Os -mcpu=arm968e-s -march=armv5te -mthumb -mthumb-interwork -ffunction-sections -fdata-sections
CCFLAGS += -flto -fno-strict-aliasing -fgnu89-inline -ffast-math -fmessage-length=0
CCFLAGS += -Wall

LKFLAGS  = -Os -mcpu=arm968e-s -mthumb -mthumb-interwork -flto -ffunction-sections -fdata-sections
LKFLAGS += -nostartfiles

CCFLAGS += -I./config \
      -I./app \
      
LKFLAGS += $(LIB_INCS)
LKFLAGS += -T./lnk/link_bim.lds
LKLIBS  += 

ASMS = app/startup_bim.S \
       app/handler_bim.S
       
SRCS = app/bim_app.c \
       app/bim_icu.c \
       app/bim_intc.c \
       app/bim_flash.c \
       app/bim_gpio.c \
       app/bim_wdt.c \
       app/bim_updataImage.c \
       app/bim_uart2.c \
       app/bim_uart0.c \
       app/bim_adc.c

OBJS := $(SRCS:%.c=$(BUILD_DIR)/%.o)
OBJS += $(SRC1:%.c=$(BUILD_DIR)/dd1/%.o)
OBJS += $(SRC2:%.c=$(BUILD_DIR)/dd2/%.o)
OBJS += $(ASMS:%.S=$(BUILD_DIR)/%.o)
DEPS := $(OBJS:.o=.d)

target: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).bin

$(BUILD_DIR)/$(TARGET).elf : $(OBJS)
    @echo Build target: $@
    @$(CC) $(LKFLAGS) -o $@ $(OBJS) $(LKLIBS)
    @echo 'Finished building target: $@'
    @echo ' '

%.bin : %.elf
    @echo Build target: $@
    @arm-none-eabi-objcopy -O binary $< $@
    @arm-none-eabi-objdump -date     $<    > $(<:%.elf=%.dmp)
    @arm-none-eabi-nm                $<    > $(<:%.elf=%.map)
ifeq ($(OS),Windows_NT)
    @cp -R ./build/$(TARGET).bin ../app_ancs/output/boot
else
    @arm-none-eabi-readelf           $< -a > $(<:%.elf=%.txt)
    @./BinConvert -crc $@
    @cp -R ./build/BK3633_BIM_crc.bin ./output
    @cp -R ./build/$(TARGET).bin ../app_ancs/output/boot
    @cp -R ./build/$(TARGET).bin ./output
endif    
    @cp -R ./build/$(TARGET).bin ../app_gatt/output/boot
    @cp -R ./build/$(TARGET).bin ../app_gatt_IRK_connect/output/boot
    @cp -R ./build/$(TARGET).bin ../app_gatt_multi_connect/output/boot
    @cp -R ./build/$(TARGET).bin ../app_multi_bond/output/boot
    @cp -R ./build/$(TARGET).bin ../app_hilink/output/boot
    @cp -R ./build/$(TARGET).bin ../app_rc/output/boot
    @cp -R ./build/$(TARGET).bin ../app_mouse/output/boot
    @cp -R ./build/$(TARGET).elf ../../src/project_files
    @echo 'Finished building target: $@'
    @echo ' '

clean:
    @echo Clean project: $(TARGET)
    @-rm -rf $(OBJS) $(DEPS) $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).bin
    -@echo ' '

prev-build:
    -@echo 'Pre-building'
    -@rm -rf $(BUILD_DIR)/$(TARGET)*.*
    -@echo ' '

post-build:
    -@echo 'Post-building'
    -@echo ' '

$(BUILD_DIR)/%.o : %.c
    @echo Compiling $<
    @mkdir -p $(dir $@)
    @$(CC) -c $(CCFLAGS) -MMD -MP -MF$(@:%.o=%.d) -MT$(@) $< -o $@

$(BUILD_DIR)/dd1/%.o : ../%.c
    @echo Compiling $<
    @mkdir -p $(dir $@)
    @$(CC) -c $(CCFLAGS) -MMD -MP -MF$(@:%.o=%.d) -MT$(@) $< -o $@

$(BUILD_DIR)/dd2/%.o : ../../%.c
    @echo Compiling $<
    @mkdir -p $(dir $@)
    @$(CC) -c $(CCFLAGS) -MMD -MP -MF$(@:%.o=%.d) -MT$(@) $< -o $@

$(BUILD_DIR)/%.o : %.S
    @echo Compiling $<
    @mkdir -p $(dir $@)
    @$(CC) -c $(CCFLAGS) -MMD -MP -MF$(@:%.o=%.d) -MT$(@) $< -o $@

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(DEPS)),)
-include $(DEPS)
endif
endif

.PHONY : all clean pre-build post-build
